FROM python:3.12-alpine
WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:0.6.6 /uv /usr/local/bin/uv

RUN adduser -D consumer && chown -R consumer /app
USER consumer

COPY --chown=consumer pyproject.toml uv.lock ./
COPY --chown=consumer services/queue-consumer/pyproject.toml ./services/queue-consumer/pyproject.toml
COPY --chown=consumer packages/shared/ ./packages/shared/
RUN uv sync --frozen --no-dev --package queue-consumer

COPY --chown=queue-consumer services/queue-consumer/ ./services/queue-consumer/

CMD ["uv", "run", "--directory", "services/queue-consumer", "main.py"]