FROM python:3.12-alpine
WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:0.6.6 /uv /usr/local/bin/uv

RUN adduser -D scraper && chown -R scraper /app
USER scraper

COPY --chown=scraper pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY --chown=scraper services/scraper/ ./

CMD ["uv", "run", "main.py"]